--- #YAML:1.0
name:               Digest-Trivial
version:            2009070801
abstract:           Trivial but fast ways to map strings to small integers
author:
    - Abigail <abigail@abigail.be>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    perl:  5.006
resources:
    repository:  git://github.com/Abigail/Digest--Trivial.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:  []
